name: vim-language-server
version: 2.3.0
summary: VimScript Language Server
description: |
  language server for VimScript

  **Features:**
  - auto completion
  - function signature help
  - hover document
  - go to definition
  - go to references
  - document symbols
  - document highlight
  - folding range
  - select range
  - rename
  - snippets
  - diagnostic

grade: stable
confinement: strict
base: core20

apps:
  vim-language-server:
    command: bin/vim-language-server
    plugs:
      - home

parts:
  vim-language-server:
    plugin: npm
    source: https://github.com/iamcco/vim-language-server.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-environment:
      - NODEJS_FIXED_VERSION: "v16.19.0"
    npm-node-version: $NODEJS_FIXED_VERSION
    override-build: |
      # install the official nodejs so we get the expected npm version
      if [ $SNAP_ARCH == "amd64" ]; then
        ARCH=x64
      elif [ $SNAP_ARCH == "armhf" ]; then
        ARCH=armv7l
      elif [ $SNAP_ARCH == "ppc64el" ]; then
        ARCH=ppc64le
      else
        ARCH=$SNAP_ARCH
      fi
      curl -s https://nodejs.org/dist/"${NODEJS_FIXED_VERSION}"/node-"${NODEJS_FIXED_VERSION}"-linux-$ARCH.tar.gz | tar xzf - -C "$SNAPCRAFT_PART_INSTALL" --strip-components=1
      npm install
      npm run build
      cp -r out $SNAPCRAFT_PART_INSTALL/lib/node_modules/vim-language-server/
      npm install -g --prefix "${SNAPCRAFT_PART_INSTALL}" $(npm pack . | tail -1)
